# Change these first
owner: piiq # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: openbb website
    url: https://openbb.co
  - name: openbb docs
    url: https://docs.openbb.co/
  - name: openbb hub
    url: $PAYMENTS_BACKEND_URL
  - name: openbb pro
    url: $OPENBB_PRO_URL
  - name: openbb pro backend
    url: $OPENBB_BACKEND_URL
  - name: openbb ada
    url: $OPENBB_AI_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  themeUrl: https://cdn.statically.io/gh/openbb-finance/uptime/master/assets/custom-theme.css
  baseUrl: /uptime
  logoUrl: https://cdn.statically.io/gh/openbb-finance/uptime/master/assets/logo.png
  name: OpenBB
  introTitle: "**OpenBB** is an enterprise AI platform for finance, empowering teams to unify data, automate research, and build custom investment workflows with full control and security."
  introMessage: "This dashboard provides uptime status of public OpenBB-managed services. Community support is available via the official OpenBB GitHub and Discord server. For status, support, and troubleshooting of your own instance, refer to your system administrator."
  favicon: https://openbb.co/favicons/favicon-32x32.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/OpenBB-finance/OpenBBTerminal
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
